### PR TITLE
Implement index signature via Proxy

### PR DESCRIPTION
**Pull request by krisztianb**
While changing some of our `string` instance variables to `UtfString` ones we came across a few bugs of this kind:

**Old code:**

```ts
const str = "asdf";
for (let i = 0; i < str.length; ++i) {
    console.log(str[i]);
}
```

**New code (broken):**

```ts
const str = new UtfString("😎");
for (let i = 0; i < str.length; ++i) {
    console.log(str[i].toString());
}
```

Since `str[i]` is going to return `undefined` the new code crashes when calling `toString()`.

This PR:

* implements the index signature using a Proxy so that the new code above works as expected
* updates the project dependencies to their latest version
* adds a HTML file to the `test/browser` folder that can be used to test the `UtfString` class in a browser

Credits go to @mjindra-tgm for investigating this problem.

### CODE REVIEW

**Comment by camertron** [comment]
Maybe I'm missing something, but why can't we define `[]` to call `charAt` instead of disallowing it entirely?

**Comment by krisztianb** [comment]
Unfortunately that is not possible to do in JavaScript. In fact the indexer code is removed by the TypeScript compiler as it is purely part of the class's type definition.

**Comment by camertron** [comment]
@krisztianb what would you think about using a `Proxy`? https://stackoverflow.com/a/25658975/498080

**Comment by krisztianb** [comment]
I'll have to take a closer look how this can be typed/used in TypeScript. Would be cool if it worked.

**Comment by krisztianb** [comment]
Got this working with the Proxy approach. Also added some tests for the new indexer. Please take a look. I think this makes the class easier to use a prevents common bugs when porting code from `string` to `UtfString`.

The huge number of "files changed" comes from moving the unit tests to a sub folder called `unit`.

**Review by camertron — APPROVED** [review]
Awesome, this is great, thank you!

**Comment by camertron** [comment]
Just published this in v3.1.0.

**Pull request merged**
