### PR TITLE
Add non-static version of UtfString

### LINKED ISSUE #9: Make UtfString non-static
Is there any reason why UtfString is a static class?

I think it would make sense to write code like this:

```js
const utfStr = new UtfString("a string in which some letters can't be represented by a JavaScript standard utf-16 string");
console.log(utfStr.length);
const anotherUtfStr = utfStr.substr(0, 5);
```

This makes it easier to spot parts of your code that are UTF-32 aware and those that are not.

### PR DESCRIPTION
**Pull request by krisztianb**
Closes #9 

## BREAKING CHANGES
* `UtfString.visual` has been moved to a separate class called `UtfVisualString`.
* Changed interface of `substring` method to use an `end` index parameter instead of a `length` parameter to match the interface of the [String.substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) method.
* `UtfString.length` is now called `UtfString.lengthOf` because of a naming conflict.
* `UtfString.fromCharCode` is now called `UtfString.stringFromCharCode` because of a naming conflict.

## Changes
* `UtfString` is now a class that can be instantiated and has its own set of string methods.
* `UtfVisualString` is now a class that can be instantiated and has its own set of string methods.

## Added
* New method `UtfString.fromBytes`: Converts an array of UTF-16 bytes into a UTF-safe string object.
* New method `UtfString.fromCharCode`: Returns a UTF-safe string object for the given Unicode codepoint.
* New method `UtfString.fromCodePoints`: Converts an array of codepoints into a UTF-safe string object.
* New method `UtfString.join`: Concatenates the strings from the given array into a new string object.
* New method `UtfString.padEnd`: Creates a new string by padding the string at the end with a given string.
* New method `UtfString.padStart`: Creates a new string by padding the string at the beginning with a given string.

## Additional Info
* Replaced `jasmine` with `mocha` for unit tests.
* Tests are now also in Typescript.
* Added lots of new unit tests. But there is still room for more handling all the possible edge cases that the "normal" string methods are also dealing with. (For example: some method treat `NaN` as `0` for some parameters)
* Added `webpack` to create the Javascript bundle for the browser version of the library. Output can be found in the new `browser` sub folder of the repo.
* New build is done by executing: `npm run build` This will compile the Typescript code to Javascript and also create a new Javascript file for the browser.
* Added `Prettier` as code formatter to unify code indentation. Checking all code files can be done by executing: `npm run format`
* Updated README and CHANGELOG.
* Bump version to `3.0.0` because of breaking changes.

### CODE REVIEW

**Review by camertron — APPROVED** [review]
What a phenomenal amount of work, thank you @krisztianb! Is this PR ready to merge?

**Comment by krisztianb** [comment]
Yes, it's ready to merge.

The class should now have most of the methods a "normal" JavaScript string has. They should also have the same interface and expected behaviour.

However some more unit tests could be added to check for edge cases and their combinations. For example [String.substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#description) treats `undefined` parameters a certain way, but if they are `NaN` they are treated as `0`. Some of these are handled but I'm not 100% sure that we got all of them. So one could check the methods another time, analyze all parameters in the documentation and add unit tests for these cases.

**Comment by camertron** [comment]
Sorry that took so long @krisztianb, published as v3.0.0 :)

**Comment by krisztianb** [comment]
Awesome. 👍

**Pull request merged**
